// Type for page metadata (used for SEO, etc.)
import type { Metadata } from "next";

// Import Google Fonts with CSS variable support
import { Geist, Geist_Mono } from "next/font/google";

// Global styles
import "./globals.css";

// Custom context providers (e.g. Auth, ImageKit)
import Providers from "./components/Providers";

// Load fonts with CSS variable names
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout for all routes
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global providers like Auth, ImageKit, etc. */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
