// Mongoose and types for schema/document handling
import mongoose, { Schema, Document, model, models } from 'mongoose';
import bcrypt from 'bcryptjs';

// User interface defining the structure of the user document
export interface IUser {
    email: string;
    password: string;
    _id?: mongoose.Types.ObjectId; // Optional _id (auto-generated by MongoDB)
    createdAt?: Date;
    updatedAt?: Date;
}

// Defining Mongoose schema for User
const UserSchema: Schema = new Schema<IUser>(
    {
        email: {
            type: String,
            required: true,       // Email must be provided
            unique: true,         // No two users can have same email
        },
        password: {
            type: String,
            required: true,       // Password is mandatory
            minlength: 6,         // Minimum password length
        },
    },
    {
        timestamps: true,         // Automatically adds createdAt & updatedAt
    }
);

// Hash the password before saving the user to DB
UserSchema.pre('save', async function (next) {
    if (this.isModified('password')) {
        this.password = await bcrypt.hash(this.password, 10); // Hash with salt rounds = 10
    }
    next();
});

// Reuse existing model if already compiled (for hot reload in dev)
const User = models?.User || model<IUser>('User', UserSchema);

// Exporting the Mongoose model
export default User;
